#Packages to install

if (!require (thinkr)) install.packages('thinkr')
library(thinkr)
if (!require (golem)) install.packages('golem')
library(golem)
if (!require(plyr)) install.packages('plyr')
library(plyr)
if (!require(dplyr)) install.packages('dplyr')
library(dplyr)
if (!require(shiny)) install.packages('shiny')
library(shiny)
if (!require(purrr)) install.packages('purrr')
library(purrr)
if (!require(stringr)) install.packages('stringr')
library(stringr)
if (!require(tidyr)) install.packages('tidyr')
library(tidyr)
if (!require(readr)) install.packages('readr')
library(readr)
if (!require(readxl)) install.packages('readxl')
library(readxl)
if (!require(knitr)) install.packages('knitr')
library(knitr)
if (!require(plotly)) install.packages('plotly')
library(plotly)
if (!require(tidyverse)) install.packages('tidyverse')
library(tidyverse)
if (!require(reshape2)) install.packages('reshape2')
library(reshape2)
if (!require(DT)) install.packages('DT')
library(DT)
if (!require(shinyjs)) install.packages('shinyjs')
library(shinyjs)